// <auto-generated />
namespace YTeDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add2class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add2class));
        
        string IMigrationMetadata.Id
        {
            get { return "202104271449463_add2class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
